plugins { id 'com.android.application' }

android {
    namespace 'com.example.books'
    compileSdk 35
    defaultConfig {
        applicationId 'com.promodeals.booksfixed'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0-fixed'
    }
}

dependencies {
    implementation 'androidx.core:core:1.15.0'
}
