plugins { id 'com.android.application' }

android {
    namespace 'com.example.books'
    compileSdk 35
    defaultConfig {
        applicationId 'com.promodeals.mybookshelf'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '1.1-reader-fix'
    }
}

dependencies {
    implementation 'androidx.core:core:1.15.0'
}
