package com.example.books;

import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.net.Uri;
import android.os.Bundle;
import android.provider.OpenableColumns;
import android.view.*;
import android.widget.*;
import androidx.core.content.FileProvider;
import java.io.*;
import java.util.*;

public class MainActivity extends Activity {
    BookDbHelper db; LinearLayout list; EditText search; Spinner filter; TextView summary; static final int PICK=77;
    int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    TextView txt(String s,int z,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(0xff20242b);if(bold)t.setTypeface(null,1);return t;}
    public void onCreate(Bundle b){super.onCreate(b);db=new BookDbHelper(this);ui();refresh();}
    void ui(){
        ScrollView sc=new ScrollView(this);LinearLayout p=new LinearLayout(this);p.setOrientation(1);p.setPadding(dp(18),dp(18),dp(18),dp(24));p.setBackgroundColor(0xfff5f3ed);sc.addView(p);
        TextView brand=txt("BOOKS  /  PERSONAL LIBRARY",13,true);brand.setTextColor(0xff49634d);p.addView(brand);
        TextView h=txt("Your bookshelf",29,true);p.addView(h);summary=txt("Your books, organized.",14,false);LinearLayout.LayoutParams sm=new LinearLayout.LayoutParams(-1,-2);sm.bottomMargin=dp(15);p.addView(summary,sm);
        Button add=new Button(this);add.setText("+ Add / import books");add.setAllCaps(false);add.setOnClickListener(v->pick());p.addView(add,new LinearLayout.LayoutParams(-1,-2));
        search=new EditText(this);search.setSingleLine(true);search.setHint("Search title, author, category");p.addView(search,new LinearLayout.LayoutParams(-1,dp(52)));
        filter=new Spinner(this);filter.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"All books","Unread","Reading","Finished","Favorites"}));p.addView(filter);
        TextView label=txt("YOUR COLLECTION",12,true);label.setTextColor(0xff657061);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(18);lp.bottomMargin=dp(8);p.addView(label,lp);
        list=new LinearLayout(this);list.setOrientation(1);p.addView(list);
        search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int before,int count){refresh();}public void afterTextChanged(android.text.Editable e){}});
        filter.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onItemSelected(AdapterView<?>a,View v,int pos,long id){refresh();}public void onNothingSelected(AdapterView<?>a){}});
        setContentView(sc);
    }
    void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"application/pdf","application/epub+zip","text/plain","application/octet-stream"});startActivityForResult(i,PICK);}
    protected void onActivityResult(int r,int result,Intent d){super.onActivityResult(r,result,d);if(r==PICK&&result==RESULT_OK&&d!=null&&d.getData()!=null){Uri u=d.getData();String name=getName(u);File dir=new File(getFilesDir(),"books");dir.mkdirs();File dest=new File(dir,System.currentTimeMillis()+"_"+name.replaceAll("[^a-zA-Z0-9._ -]","_"));try(InputStream in=getContentResolver().openInputStream(u);OutputStream out=new FileOutputStream(dest)){if(in==null)throw new IOException("Cannot read file");byte[] buf=new byte[8192];int n;while((n=in.read(buf))>0)out.write(buf,0,n);db.add(name,dest.getAbsolutePath());refresh();Toast.makeText(this,"Book imported",0).show();}catch(Exception e){Toast.makeText(this,"Import failed: "+e.getMessage(),1).show();}}}
    String getName(Uri u){try(Cursor c=getContentResolver().query(u,null,null,null,null)){if(c!=null&&c.moveToFirst()){int x=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(x>=0)return c.getString(x);}}catch(Exception ignored){}return "Imported book";}
    void refresh(){if(list==null||db==null)return;list.removeAllViews();String f=filter==null||filter.getSelectedItem()==null?"All books":filter.getSelectedItem().toString();List<BookDbHelper.Book> bs=db.all(search==null?"":search.getText().toString(),f);summary.setText(db.count()+" books stored on this device");if(bs.isEmpty()){TextView e=txt("Your shelf is empty. Tap Add / import books to choose a file from Google Files or another file picker.",15,false);e.setPadding(dp(15),dp(20),dp(15),dp(20));e.setBackgroundColor(-1);list.addView(e);return;}for(BookDbHelper.Book b:bs){LinearLayout c=new LinearLayout(this);c.setOrientation(1);c.setPadding(dp(13),dp(12),dp(13),dp(12));c.setBackgroundColor(-1);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.bottomMargin=dp(10);list.addView(c,cp);c.addView(txt((b.favorite==1?"★ ":"")+b.title,18,true));TextView meta=txt((b.author.isEmpty()?"Author not set":b.author)+" · "+b.category,13,false);c.addView(meta);c.addView(txt(b.status+" · "+b.progress+"% complete",13,false));LinearLayout row=new LinearLayout(this);Button open=new Button(this);open.setText("Open");open.setAllCaps(false);open.setOnClickListener(v->openBook(b));row.addView(open,new LinearLayout.LayoutParams(0,dp(46),1));Button details=new Button(this);details.setText("Details");details.setAllCaps(false);details.setOnClickListener(v->edit(b));row.addView(details,new LinearLayout.LayoutParams(0,dp(46),1));Button more=new Button(this);more.setText("⋮");more.setOnClickListener(v->menu(b));row.addView(more,new LinearLayout.LayoutParams(dp(48),dp(46)));c.addView(row);}}
    String mime(String n){n=n.toLowerCase(Locale.ROOT);if(n.endsWith(".pdf"))return "application/pdf";if(n.endsWith(".epub"))return "application/epub+zip";if(n.endsWith(".txt"))return "text/plain";return "*/*";}
    void openBook(BookDbHelper.Book b){try{Uri u=FileProvider.getUriForFile(this,getPackageName()+".provider",new File(b.path));Intent i=new Intent(Intent.ACTION_VIEW);i.setDataAndType(u,mime(b.path));i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(i);}catch(Exception e){Toast.makeText(this,"Install a compatible PDF or ebook reader.",1).show();}}
    void share(BookDbHelper.Book b){try{Uri u=FileProvider.getUriForFile(this,getPackageName()+".provider",new File(b.path));Intent i=new Intent(Intent.ACTION_SEND);i.setType(mime(b.path));i.putExtra(Intent.EXTRA_STREAM,u);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"Share book"));}catch(Exception e){Toast.makeText(this,"Could not share file",0).show();}}
    void menu(BookDbHelper.Book b){String[] a={b.favorite==1?"Remove favorite":"Add favorite","Reading status","Share file","Delete book"};new AlertDialog.Builder(this).setTitle(b.title).setItems(a,(d,w)->{if(w==0){b.favorite=1-b.favorite;db.update(b);refresh();}else if(w==1)new AlertDialog.Builder(this).setTitle("Reading status").setItems(new String[]{"Unread","Reading","Finished"},(x,y)->{b.status=new String[]{"Unread","Reading","Finished"}[y];if(y==0)b.progress=0;if(y==2)b.progress=100;db.update(b);refresh();}).show();else if(w==2)share(b);else new AlertDialog.Builder(this).setMessage("Delete this book and its stored file?").setNegativeButton("Cancel",null).setPositiveButton("Delete",(x,y)->{new File(b.path).delete();db.delete(b.id);refresh();}).show();}).show();}
    void edit(BookDbHelper.Book b){LinearLayout form=new LinearLayout(this);form.setPadding(dp(15),0,dp(15),0);form.setOrientation(1);EditText t=field(form,"Title",b.title,false),a=field(form,"Author",b.author,false),cat=field(form,"Category",b.category,false),pr=field(form,"Progress (0–100)",String.valueOf(b.progress),true),ra=field(form,"Rating (0–5)",String.valueOf(b.rating),true),no=field(form,"Notes",b.notes,false);no.setMinLines(2);new AlertDialog.Builder(this).setTitle("Book details").setView(form).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{b.title=val(t,"Untitled book");b.author=val(a,"");b.category=val(cat,"Uncategorized");b.notes=no.getText().toString();try{b.progress=Math.max(0,Math.min(100,Integer.parseInt(pr.getText().toString())));}catch(Exception ignored){}try{b.rating=Math.max(0,Math.min(5,Integer.parseInt(ra.getText().toString())));}catch(Exception ignored){}if(b.progress==100)b.status="Finished";else if(b.progress>0)b.status="Reading";db.update(b);refresh();}).show();}
    EditText field(LinearLayout p,String hint,String value,boolean numeric){EditText e=new EditText(this);e.setSingleLine(!hint.equals("Notes"));e.setHint(hint);e.setText(value==null?"":value);if(numeric)e.setInputType(2);p.addView(e);return e;}
    String val(EditText e,String fallback){String s=e.getText().toString().trim();return s.isEmpty()?fallback:s;}
}
