package com.example.books;
import android.app.Activity;import android.graphics.*;import android.graphics.pdf.PdfRenderer;import android.os.*;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;import java.util.concurrent.*;
public class PdfViewerActivity extends Activity{
 public static final String EXTRA_PATH="pdf_path",EXTRA_TITLE="pdf_title"; ParcelFileDescriptor fd;PdfRenderer renderer;ExecutorService worker;LinearLayout pages;ScrollView scroll;TextView status;ArrayList<PV> views=new ArrayList<>();ArrayList<int[]> dims=new ArrayList<>();volatile boolean closing=false;float zoom=1;int width;
 int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
 TextView label(String s,int z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(0xff263244);return t;}
 Button button(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}
 public void onCreate(Bundle b){super.onCreate(b);worker=Executors.newSingleThreadExecutor();String path=getIntent().getStringExtra(EXTRA_PATH),title=getIntent().getStringExtra(EXTRA_TITLE);setTitle(title==null?"PDF Reader":title);
 LinearLayout root=new LinearLayout(this);root.setOrientation(1);root.setBackgroundColor(0xffeef1f5);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.setPadding(dp(12),dp(8),dp(8),dp(8));head.addView(label(title==null?"PDF Reader":title,16),new LinearLayout.LayoutParams(0,-2,1));status=label("Preparing PDF…",11);head.addView(status);root.addView(head);
 LinearLayout bar=new LinearLayout(this);Button minus=button("−"),fit=button("Fit page"),plus=button("+");bar.addView(minus,new LinearLayout.LayoutParams(dp(50),dp(42)));bar.addView(fit,new LinearLayout.LayoutParams(0,dp(42),1));bar.addView(plus,new LinearLayout.LayoutParams(dp(50),dp(42)));root.addView(bar);minus.setOnClickListener(v->zoom(zoom*.8f));plus.setOnClickListener(v->zoom(zoom*1.25f));fit.setOnClickListener(v->zoom(1));
 pages=new LinearLayout(this);pages.setOrientation(1);pages.setPadding(dp(8),dp(8),dp(8),dp(12));scroll=new ScrollView(this);scroll.addView(pages);scroll.setOnScrollChangeListener((View v,int x,int y,int ox,int oy)->visible());HorizontalScrollView h=new HorizontalScrollView(this);h.addView(scroll,new HorizontalScrollView.LayoutParams(-1,-1));root.addView(h,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);
 if(path==null||!new File(path).isFile()){error("PDF file not found. Import it again.");return;}worker.execute(()->{try{ParcelFileDescriptor d=ParcelFileDescriptor.open(new File(path),ParcelFileDescriptor.MODE_READ_ONLY);PdfRenderer r=new PdfRenderer(d);ArrayList<int[]> sz=new ArrayList<>();for(int i=0;i<r.getPageCount();i++){if(closing){r.close();d.close();return;}PdfRenderer.Page p=r.openPage(i);sz.add(new int[]{p.getWidth(),p.getHeight()});p.close();}runOnUiThread(()->{if(closing){try{r.close();d.close();}catch(Exception e){}return;}fd=d;renderer=r;dims.addAll(sz);width=Math.max(dp(180),Math.min(dp(850),getResources().getDisplayMetrics().widthPixels-dp(36)));for(int i=0;i<dims.size();i++){PV p=new PV(i);views.add(p);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(width,height(i));lp.gravity=Gravity.CENTER_HORIZONTAL;lp.bottomMargin=dp(10);pages.addView(p,lp);}status.setText(sz.size()+" pages · loading as needed");visible();});}catch(Exception e){runOnUiThread(()->error("Could not open this PDF. It may be damaged or unsupported."));}});}
 int height(int i){return Math.max(dp(100),(int)(width*dims.get(i)[1]/(float)Math.max(1,dims.get(i)[0])));}
 void visible(){if(closing||renderer==null)return;int t=scroll.getScrollY(),b=t+scroll.getHeight(),m=scroll.getHeight();for(PV p:views){if(p.getTop()+p.getHeight()>=t-m&&p.getTop()<=b+m)p.load();else p.release();}}
 void zoom(float z){zoom=Math.max(1,Math.min(3,z));for(PV p:views){ViewGroup.LayoutParams lp=p.getLayoutParams();lp.width=(int)(width*zoom);lp.height=(int)(height(p.i)*zoom);p.setLayoutParams(lp);p.release();}status.setText("Zoom "+Math.round(zoom*100)+"%");visible();}
 void error(String s){status.setText("PDF error");pages.addView(label(s,15));}
 class PV extends View{int i;Bitmap bmp;boolean loading,failed;Paint paint=new Paint(3);ScaleGestureDetector detector;PV(int n){super(PdfViewerActivity.this);i=n;setBackgroundColor(-1);detector=new ScaleGestureDetector(PdfViewerActivity.this,new ScaleGestureDetector.SimpleOnScaleGestureListener(){public boolean onScale(ScaleGestureDetector d){zoom(zoom*d.getScaleFactor());return true;}});}
 boolean wanted(){int t=scroll.getScrollY(),b=t+scroll.getHeight();return getTop()+getHeight()>=t-scroll.getHeight()&&getTop()<=b+scroll.getHeight()&&!closing;}
 void load(){if(bmp!=null||loading||failed||renderer==null)return;loading=true;int target=getWidth()>0?getWidth():width;int w=Math.max(240,Math.min(900,(int)(target*1.05f)));worker.execute(()->{Bitmap out=null;PdfRenderer.Page p=null;String problem=null;try{if(!closing){p=renderer.openPage(i);int rw=w,rh=Math.max(1,(int)(rw*p.getHeight()/(float)Math.max(1,p.getWidth())));long bytes=(long)rw*rh*2;if(bytes>12L*1024*1024){float f=(float)Math.sqrt(12L*1024*1024/(double)bytes);rw=Math.max(1,(int)(rw*f));rh=Math.max(1,(int)(rh*f));}try{out=Bitmap.createBitmap(rw,rh,Bitmap.Config.RGB_565);out.eraseColor(Color.WHITE);p.render(out,null,null,PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY);}catch(OutOfMemoryError oom){if(out!=null){out.recycle();out=null;}rw=Math.max(160,rw/2);rh=Math.max(1,(int)(rw*p.getHeight()/(float)Math.max(1,p.getWidth())));out=Bitmap.createBitmap(rw,rh,Bitmap.Config.RGB_565);out.eraseColor(Color.WHITE);p.render(out,null,null,PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY);}}}catch(Exception e){problem=e.getClass().getSimpleName()+": "+String.valueOf(e.getMessage());if(out!=null&&!out.isRecycled())out.recycle();out=null;}catch(OutOfMemoryError e){problem="Not enough memory";if(out!=null&&!out.isRecycled())out.recycle();out=null;}finally{if(p!=null)p.close();}final Bitmap result=out;final String err=problem;runOnUiThread(()->{loading=false;if(!wanted()){if(result!=null&&!result.isRecycled())result.recycle();return;}if(result==null){failed=false;status.setText("Page "+(i+1)+" render failed"+(err==null?"":" · "+err));postDelayed(()->{if(wanted()&&bmp==null&&!loading)load();},1200);}else{failed=false;bmp=result;}invalidate();});});}
 void release(){if(bmp!=null){if(!bmp.isRecycled())bmp.recycle();bmp=null;invalidate();}}
 protected void onDraw(Canvas c){super.onDraw(c);c.drawColor(-1);if(bmp!=null&&!bmp.isRecycled())c.drawBitmap(bmp,null,new RectF(0,0,getWidth(),getHeight()),paint);else{paint.setColor(0xff64748b);paint.setTextSize(dp(13));c.drawText(failed?"Page unavailable":loading?"Loading page…":"Page loads when visible",dp(12),Math.max(dp(24),getHeight()/2f),paint);}}
 public boolean onTouchEvent(MotionEvent e){detector.onTouchEvent(e);return true;}}
 protected void onDestroy(){closing=true;for(PV p:views)p.release();if(worker!=null)worker.shutdownNow();PdfRenderer r=renderer;ParcelFileDescriptor d=fd;if(r!=null||d!=null)new Thread(()->{try{if(r!=null)r.close();}catch(Exception e){}try{if(d!=null)d.close();}catch(Exception e){}}).start();super.onDestroy();}
}